### ISSUE TITLE
query on current status

### ISSUE THREAD

**Issue by moha23** [astolap/WaSP#7]
Hi,

I tried building the software in linux, tried fixing errors but it is still failing. A few questions, is this repo maintained or is there a JPEG Pleno reference software one can use to run experiments? If not, could you possibly have published test results on all the images in the JPEG Pleno database? I found your WaSP paper but that reports on a couple of the test sets only. It would be great if i could run the software.

The current error:

    source/ppm.cpp: In function ‘bool aux_read16PGMPPM(const char*, int32_t&, int32_t&, int32_t&, uint16_t*&)’:
    source/ppm.cpp:60:9: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute   warn_unused_result [-Wunused-result]
       60 |   fscanf(filept, "%s", dummy);
          |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~
    source/ppm.cpp:61:9: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute    warn_unused_result [-Wunused-result]
        61 |   fscanf(filept, "%d %d\n", &width, &height);
          |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    source/ppm.cpp:62:9: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute   warn_unused_result [-Wunused-result]
       62 |   fscanf(filept, "%d", &max);
           |   ~~~~~~^~~~~~~~~~~~~~~~~~~~
    source/residualjp2.cpp: In function ‘void writeResidualToDisk(const char*, FILE*, int32_t&, std::vector<std::vector<unsigned char> >&)’:
    source/residualjp2.cpp:177:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
      177 |   fread(jp2_residual, sizeof(uint8_t), n_bytes_JP2,
          |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      178 |         jp2_color_residual_file);
          |         ~~~~~~~~~~~~~~~~~~~~~~~~
     /usr/bin/ld: /tmp/cccpULDv.o: in function `main':
    /home/mo/Documents/WaSP-master/source/wasp-encoder.cpp:30: multiple definition of `main'; source/wasp-encoder.o:wasp-encoder.cpp:(.text+0x0): first defined here
    /usr/bin/ld: /tmp/cccpULDv.o: in function `main':
    wasp-encoder.cpp:(.text.startup+0x13b): undefined reference to `encoder::encoder(WaSPsetup)'
    /usr/bin/ld: wasp-encoder.cpp:(.text.startup+0x14b): undefined reference to `encoder::encode()'
    /usr/bin/ld: /tmp/cccpULDv.o: in function `main.cold':
    /home/mo/Documents/WaSP-master/source/wasp-encoder.cpp:34: undefined reference to `encoder::~encoder()'
    /usr/bin/ld: source/wasp-encoder.o: in function `main':
    wasp-encoder.cpp:(.text+0x81): undefined reference to `encoder::encoder(WaSPsetup)'
    /usr/bin/ld: wasp-encoder.cpp:(.text+0x9f): undefined reference to `encoder::encode()'
    /usr/bin/ld: wasp-encoder.cpp:(.text+0xd7): undefined reference to `encoder::~encoder()'
    collect2: error: ld returned 1 exit status
    make: *** [makefile:11: wasp-encoder-bin] Error 1

**Comment by astolap** [comment]
Makefile was indeed broken and has been corrected now.
